[package]
name = "app-streaming"
version = "0.1.0"
authors = ["greenknot"]

[[bin]]
name = "app"
path = "src/app.rs"

[dependencies]
hex = "0.4.3"
hex-literal = "0.3.4"
rust-crypto = "0.2.36"
zip = "0.6.2"
