# Build the VM app

name: VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: vm/

jobs:
  build:
    name: Clang Static Analyzer
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Lint tests
        run: |
          find tests/ -name '*.[ch]' -exec clang-format -style=file -Werror --dry-run '{}' '+'

      - name: Tests
        run: |
          cmake -Bbuild -Htests/
          make -C build/
          make -C build/ test

      - name: Build
        run: |
          make BOLOS_SDK=$NANOX_SDK

      - name: Build with Clang Static Analyzer
        run: |
          scan-build --use-cc=clang -analyze-headers -enable-checker security -enable-checker unix -enable-checker valist -o scan-build --status-bugs make BOLOS_SDK=$NANOX_SDK
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: scan-build
          path: scan-build
